// ============================================================
// PATHORA — Complete Mock Data
// ============================================================

export const demoUser = {
  id: "demo-001",
  name: "Aryan Mehta",
  email: "aryan.mehta@gmail.com",
  avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Aryan",
  nationality: "Indian",
  degree: "Computer Science",
  cgpa: 8.4,
  ielts: 7.5,
  budget: 25000,
  workExp: 1,
  targetDegree: "MS",
  interestedFields: ["AI/ML", "Data Science", "Software Engineering"],
  targetYear: 2025,
  joinedAt: "2024-01-15",
  referralCode: "ARYAN2024",
  referrals: 7,
};

export const countries = [
  {
    id: "germany",
    name: "Germany",
    flag: "🇩🇪",
    code: "DE",
    score: 94,
    rank: 1,
    tagline: "Europe's Tech Powerhouse",
    image: "https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=800",
    gdp: "$4.1T",
    gdpGrowth: "+2.1%",
    avgSalary: "€58,000",
    avgSalaryINR: "₹52L",
    livingCost: "€1,100/mo",
    visaDifficulty: "Medium",
    visaDifficultyScore: 55,
    prScore: 88,
    safetyScore: 91,
    healthcareScore: 89,
    educationScore: 93,
    partTimeRights: "20 hrs/week",
    language: "German + English",
    weather: "Temperate",
    currency: "EUR",
    timezone: "CET (UTC+1)",
    population: "84M",
    topCities: ["Berlin", "Munich", "Hamburg", "Frankfurt", "Stuttgart"],
    jobMarket: "Excellent",
    jobGrowth: "+4.2%",
    topSectors: ["Engineering", "Automotive", "IT", "Finance", "Healthcare"],
    visaTypes: ["Student Visa", "Job Seeker Visa", "EU Blue Card"],
    universities: 48,
    scholarships: 230,
    avgTuition: "€1,500/yr",
    acceptanceRate: "65%",
    pr: {
      eligible: true,
      years: 5,
      path: "EU Blue Card → PR",
      difficulty: "Medium",
    },
    pros: ["Free/low tuition", "Strong job market", "PR pathway", "English programs"],
    cons: ["Language barrier", "Bureaucracy", "Cold winters", "Housing shortage"],
    roi: "+340%",
    paybackYears: 2.3,
    overview: "Germany is the top destination for STEM graduates seeking world-class education with minimal tuition fees and excellent career prospects in Europe's largest economy.",
  },
  {
    id: "canada",
    name: "Canada",
    flag: "🇨🇦",
    code: "CA",
    score: 91,
    rank: 2,
    tagline: "Immigration-Friendly Tech Hub",
    image: "https://images.unsplash.com/photo-1517935706615-2717063c2225?w=800",
    gdp: "$2.1T",
    gdpGrowth: "+2.4%",
    avgSalary: "CAD $85,000",
    avgSalaryINR: "₹51L",
    livingCost: "CAD $2,200/mo",
    visaDifficulty: "Easy",
    visaDifficultyScore: 35,
    prScore: 96,
    safetyScore: 94,
    healthcareScore: 88,
    educationScore: 90,
    partTimeRights: "20 hrs/week",
    language: "English + French",
    weather: "Varied",
    currency: "CAD",
    timezone: "EST/PST",
    population: "38M",
    topCities: ["Toronto", "Vancouver", "Montreal", "Calgary", "Ottawa"],
    jobMarket: "Very Good",
    jobGrowth: "+3.8%",
    topSectors: ["Tech", "Finance", "Healthcare", "Engineering", "AI"],
    visaTypes: ["Study Permit", "PGWP", "Express Entry"],
    universities: 96,
    scholarships: 410,
    avgTuition: "CAD $28,000/yr",
    acceptanceRate: "55%",
    pr: {
      eligible: true,
      years: 3,
      path: "PGWP → Express Entry → PR",
      difficulty: "Easy",
    },
    pros: ["Easy PR", "Multicultural", "High quality of life", "Strong economy"],
    cons: ["High tuition", "Cold winters", "Expensive housing", "Competitive market"],
    roi: "+280%",
    paybackYears: 3.1,
    overview: "Canada offers the clearest pathway to permanent residency for international students, with post-graduation work permits and Express Entry immigration system.",
  },
  {
    id: "uk",
    name: "United Kingdom",
    flag: "🇬🇧",
    code: "GB",
    score: 87,
    rank: 3,
    tagline: "World-Class Prestige",
    image: "https://images.unsplash.com/photo-1486299267070-83823f5448dd?w=800",
    gdp: "$3.1T",
    gdpGrowth: "+1.8%",
    avgSalary: "£52,000",
    avgSalaryINR: "₹55L",
    livingCost: "£1,800/mo",
    visaDifficulty: "Medium",
    visaDifficultyScore: 50,
    prScore: 72,
    safetyScore: 85,
    healthcareScore: 86,
    educationScore: 96,
    partTimeRights: "20 hrs/week",
    language: "English",
    weather: "Rainy/Mild",
    currency: "GBP",
    timezone: "GMT (UTC+0)",
    population: "67M",
    topCities: ["London", "Manchester", "Edinburgh", "Birmingham", "Bristol"],
    jobMarket: "Good",
    jobGrowth: "+2.1%",
    topSectors: ["Finance", "Tech", "Healthcare", "Consulting", "Media"],
    visaTypes: ["Student Visa", "Graduate Visa", "Skilled Worker Visa"],
    universities: 162,
    scholarships: 580,
    avgTuition: "£25,000/yr",
    acceptanceRate: "62%",
    pr: {
      eligible: true,
      years: 5,
      path: "Graduate Route → Skilled Worker → ILR",
      difficulty: "Hard",
    },
    pros: ["Prestigious universities", "2-yr PSW", "English-speaking", "Global brand"],
    cons: ["Very expensive", "Brexit uncertainty", "Hard PR", "High living costs"],
    roi: "+220%",
    paybackYears: 3.8,
    overview: "The UK offers unmatched academic prestige with institutions like Oxford and Cambridge, plus a 2-year post-study work visa for international graduates.",
  },
  {
    id: "australia",
    name: "Australia",
    flag: "🇦🇺",
    code: "AU",
    score: 85,
    rank: 4,
    tagline: "Sunny Gateway to APAC",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800",
    gdp: "$1.7T",
    gdpGrowth: "+2.6%",
    avgSalary: "AUD $90,000",
    avgSalaryINR: "₹48L",
    livingCost: "AUD $2,500/mo",
    visaDifficulty: "Medium",
    visaDifficultyScore: 45,
    prScore: 82,
    safetyScore: 93,
    healthcareScore: 90,
    educationScore: 88,
    partTimeRights: "48 hrs/fortnight",
    language: "English",
    weather: "Sunny/Warm",
    currency: "AUD",
    timezone: "AEST (UTC+10)",
    population: "26M",
    topCities: ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide"],
    jobMarket: "Very Good",
    jobGrowth: "+3.5%",
    topSectors: ["Mining", "Tech", "Healthcare", "Finance", "Education"],
    visaTypes: ["Student Visa", "Temporary Graduate", "Skilled Nominated"],
    universities: 43,
    scholarships: 290,
    avgTuition: "AUD $35,000/yr",
    acceptanceRate: "70%",
    pr: {
      eligible: true,
      years: 4,
      path: "Temporary Graduate → Skilled → PR",
      difficulty: "Medium",
    },
    pros: ["Great lifestyle", "English-speaking", "PR pathway", "Strong economy"],
    cons: ["Far from home", "Expensive", "Limited PR spots", "Competitive"],
    roi: "+260%",
    paybackYears: 3.4,
    overview: "Australia combines world-class education with an exceptional quality of life and clear immigration pathways for skilled professionals.",
  },
  {
    id: "netherlands",
    name: "Netherlands",
    flag: "🇳🇱",
    code: "NL",
    score: 82,
    rank: 5,
    tagline: "Europe's English-Friendly Hub",
    image: "https://images.unsplash.com/photo-1512470876302-972faa2aa9a4?w=800",
    gdp: "$1.1T",
    gdpGrowth: "+2.2%",
    avgSalary: "€62,000",
    avgSalaryINR: "₹56L",
    livingCost: "€1,400/mo",
    visaDifficulty: "Easy",
    visaDifficultyScore: 30,
    prScore: 80,
    safetyScore: 92,
    healthcareScore: 91,
    educationScore: 90,
    partTimeRights: "16 hrs/week",
    language: "English + Dutch",
    weather: "Mild/Rainy",
    currency: "EUR",
    timezone: "CET (UTC+1)",
    population: "17.9M",
    topCities: ["Amsterdam", "Rotterdam", "The Hague", "Utrecht", "Eindhoven"],
    jobMarket: "Excellent",
    jobGrowth: "+3.9%",
    topSectors: ["Tech", "Finance", "Logistics", "Agriculture", "AI"],
    visaTypes: ["Student Visa", "Orientation Year", "Highly Skilled Migrant"],
    universities: 18,
    scholarships: 160,
    avgTuition: "€10,000/yr",
    acceptanceRate: "72%",
    pr: {
      eligible: true,
      years: 5,
      path: "Orientation Year → HSM → PR",
      difficulty: "Medium",
    },
    pros: ["English programs", "Orientation year visa", "Amsterdam hub", "Cycling culture"],
    cons: ["Expensive housing", "Dutch required for PR", "Small country", "Weather"],
    roi: "+310%",
    paybackYears: 2.8,
    overview: "Netherlands offers the best of European education with nearly all programs taught in English and the Orientation Year visa for job searching after graduation.",
  },
  {
    id: "sweden",
    name: "Sweden",
    flag: "🇸🇪",
    code: "SE",
    score: 79,
    rank: 6,
    tagline: "Innovation Capital of Scandinavia",
    image: "https://images.unsplash.com/photo-1509356843151-3e7d96241e11?w=800",
    gdp: "$0.6T",
    gdpGrowth: "+1.9%",
    avgSalary: "SEK 480,000",
    avgSalaryINR: "₹37L",
    livingCost: "SEK 12,000/mo",
    visaDifficulty: "Medium",
    visaDifficultyScore: 50,
    prScore: 75,
    safetyScore: 95,
    healthcareScore: 93,
    educationScore: 88,
    partTimeRights: "Unlimited",
    language: "Swedish + English",
    weather: "Cold/Snowy",
    currency: "SEK",
    timezone: "CET (UTC+1)",
    population: "10.5M",
    topCities: ["Stockholm", "Gothenburg", "Malmö", "Uppsala", "Linköping"],
    jobMarket: "Good",
    jobGrowth: "+2.8%",
    topSectors: ["Gaming", "Telecom", "Fintech", "Clean Energy", "Medtech"],
    visaTypes: ["Residence Permit", "Job Seeker", "Self Employment"],
    universities: 38,
    scholarships: 140,
    avgTuition: "SEK 120,000/yr",
    acceptanceRate: "68%",
    pr: {
      eligible: true,
      years: 5,
      path: "Permit → Permanent Residence",
      difficulty: "Medium",
    },
    pros: ["Innovation ecosystem", "Work-life balance", "Unlimited work rights", "Safety"],
    cons: ["Language barrier", "Cold winters", "High taxes", "Expensive"],
    roi: "+220%",
    paybackYears: 3.9,
    overview: "Sweden is home to global tech giants like Spotify, Klarna and Ericsson, offering incredible opportunities in the heart of Scandinavia's innovation ecosystem.",
  },
];

export const universities = [
  {
    id: "tum",
    countryId: "germany",
    name: "Technical University of Munich",
    shortName: "TUM",
    location: "Munich, Germany",
    image: "https://images.unsplash.com/photo-1562774053-701939374585?w=800",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Logo_of_the_Technical_University_of_Munich.svg/200px-Logo_of_the_Technical_University_of_Munich.svg.png",
    rank: 50,
    qsRank: "#50 QS 2024",
    type: "Public",
    founded: 1868,
    students: 50000,
    intlStudents: 35,
    tuitionFee: "€0/yr",
    livingCost: "€1,100/mo",
    acceptanceRate: 32,
    programs: ["MS Computer Science", "MS Data Science", "MS Electrical Engineering", "MS Robotics", "MBA"],
    scholarships: ["DAAD", "Deutschland Stipendium", "TUM Merit Scholarship"],
    deadlines: { winter: "May 31, 2025", summer: "Nov 30, 2025" },
    ielts: 6.5,
    gre: "Not Required",
    avgSalary: "€65,000",
    employmentRate: 97,
    avgTimeToJob: "3 months",
    researchOutput: "Top 5% globally",
    nobelLaureates: 17,
    industry: "Siemens, BMW, Allianz (campus recruiting)",
    campusLife: "Vibrant, international, 180+ clubs",
    housing: "€400-600/mo student dorms",
    rating: 4.7,
    reviews: [
      { name: "Priya S.", text: "Best decision of my life. Professors are incredible, research facilities are top-notch.", rating: 5 },
      { name: "Rahul K.", text: "Job placements are excellent. Got hired by Siemens within 2 months of graduating.", rating: 5 },
      { name: "Sneha M.", text: "Free tuition is unbelievable. Pay only semester fees of ~€140.", rating: 4 },
    ],
    tags: ["STEM", "Research", "Free Tuition", "QS Top 100"],
    matchScore: 94,
    pros: ["World-class research", "Zero tuition", "BMW & Siemens partnerships", "English programs"],
    cons: ["Competitive admission", "German language useful", "Munich is expensive"],
    applyUrl: "#",
    videoTour: "#",
  },
  {
    id: "rwth",
    countryId: "germany",
    name: "RWTH Aachen University",
    shortName: "RWTH",
    location: "Aachen, Germany",
    image: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800",
    rank: 106,
    qsRank: "#106 QS 2024",
    type: "Public",
    founded: 1870,
    students: 45000,
    intlStudents: 28,
    tuitionFee: "€0/yr",
    livingCost: "€900/mo",
    acceptanceRate: 42,
    programs: ["MS Computer Science", "MS Mechanical Engineering", "MS Data Science"],
    scholarships: ["DAAD", "Aachen Excellence Scholarship"],
    deadlines: { winter: "June 15, 2025", summer: "Dec 15, 2025" },
    ielts: 6.5,
    gre: "Not Required",
    avgSalary: "€62,000",
    employmentRate: 95,
    avgTimeToJob: "4 months",
    researchOutput: "Top 8% globally",
    nobelLaureates: 8,
    industry: "Ford, Thyssen Krupp, local tech startups",
    campusLife: "Engineer-focused, strong clubs",
    housing: "€350-500/mo student housing",
    rating: 4.5,
    reviews: [
      { name: "Vikram P.", text: "Engineering paradise. The faculty-industry connection is amazing.", rating: 5 },
      { name: "Anika R.", text: "Cheaper city than Munich but same quality education.", rating: 4 },
    ],
    tags: ["Engineering", "Research", "Free Tuition", "Affordable"],
    matchScore: 88,
    pros: ["Top engineering school", "Free tuition", "Affordable city", "Strong industry links"],
    cons: ["Smaller city", "Less diverse", "German required for daily life"],
    applyUrl: "#",
    videoTour: "#",
  },
  {
    id: "uoft",
    countryId: "canada",
    name: "University of Toronto",
    shortName: "UofT",
    location: "Toronto, Ontario",
    image: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800",
    rank: 21,
    qsRank: "#21 QS 2024",
    type: "Public",
    founded: 1827,
    students: 95000,
    intlStudents: 27,
    tuitionFee: "CAD $30,000/yr",
    livingCost: "CAD $2,200/mo",
    acceptanceRate: 43,
    programs: ["MEng Computer Engineering", "MScAC", "MS Statistics", "MBA Rotman"],
    scholarships: ["Lester B. Pearson", "UofT Masters Award", "Trudeau Scholarship"],
    deadlines: { winter: "Feb 1, 2025", summer: "N/A" },
    ielts: 6.5,
    gre: "Optional",
    avgSalary: "CAD $110,000",
    employmentRate: 94,
    avgTimeToJob: "2 months",
    researchOutput: "Top 3% globally",
    nobelLaureates: 10,
    industry: "Google, Amazon, Shopify, TD Bank (campus recruiting)",
    campusLife: "Massive, diverse, 1000+ clubs",
    housing: "CAD $800-1500/mo",
    rating: 4.6,
    reviews: [
      { name: "Meera N.", text: "Incredible network. Met co-founders here. Toronto tech scene is booming.", rating: 5 },
      { name: "Arjun T.", text: "Tough to get in but worth every penny. Career services are exceptional.", rating: 4 },
    ],
    tags: ["Research", "Top 25", "AI Hub", "Diversity"],
    matchScore: 91,
    pros: ["Top 25 globally", "Toronto tech ecosystem", "PGWP eligible", "Diverse"],
    cons: ["Very expensive", "Competitive", "High cost of living"],
    applyUrl: "#",
    videoTour: "#",
  },
  {
    id: "imperial",
    countryId: "uk",
    name: "Imperial College London",
    shortName: "Imperial",
    location: "London, UK",
    image: "https://images.unsplash.com/photo-1534430480872-3498386e7856?w=800",
    rank: 6,
    qsRank: "#6 QS 2024",
    type: "Public",
    founded: 1907,
    students: 20000,
    intlStudents: 59,
    tuitionFee: "£35,000/yr",
    livingCost: "£2,000/mo",
    acceptanceRate: 14,
    programs: ["MSc Computing", "MSc AI", "MSc Data Science", "MSc Bioengineering"],
    scholarships: ["President's Scholarship", "Schrödinger Scholarship", "Imperial-GREAT"],
    deadlines: { winter: "March 31, 2025", summer: "N/A" },
    ielts: 7.0,
    gre: "Not Required",
    avgSalary: "£75,000",
    employmentRate: 98,
    avgTimeToJob: "1.5 months",
    researchOutput: "Top 1% globally",
    nobelLaureates: 16,
    industry: "Goldman Sachs, McKinsey, DeepMind, Google (campus)",
    campusLife: "Intense but rewarding, London lifestyle",
    housing: "£1,200-2,000/mo",
    rating: 4.8,
    reviews: [
      { name: "Aditya B.", text: "Best AI program in the world. Professors literally worked at DeepMind.", rating: 5 },
      { name: "Prerna S.", text: "London is expensive but the alumni network is priceless.", rating: 5 },
    ],
    tags: ["Elite", "Top 10", "AI", "Research Excellence"],
    matchScore: 78,
    pros: ["Top 10 globally", "London location", "Elite alumni", "99% placement"],
    cons: ["Very expensive", "High competition", "Intense workload", "Hard to get in"],
    applyUrl: "#",
    videoTour: "#",
  },
  {
    id: "tue",
    countryId: "netherlands",
    name: "TU Eindhoven",
    shortName: "TU/e",
    location: "Eindhoven, Netherlands",
    image: "https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=800",
    rank: 177,
    qsRank: "#177 QS 2024",
    type: "Public",
    founded: 1956,
    students: 15000,
    intlStudents: 40,
    tuitionFee: "€17,000/yr",
    livingCost: "€1,100/mo",
    acceptanceRate: 55,
    programs: ["MSc Data Science", "MSc AI", "MSc Computer Science & Engineering"],
    scholarships: ["Orange Tulip Scholarship", "TU/e Excellence Scholarship"],
    deadlines: { winter: "April 1, 2025", summer: "N/A" },
    ielts: 6.5,
    gre: "Not Required",
    avgSalary: "€58,000",
    employmentRate: 92,
    avgTimeToJob: "3 months",
    researchOutput: "Top 15% globally",
    nobelLaureates: 2,
    industry: "ASML, Philips, DAF, NXP (campus partnerships)",
    campusLife: "Tech-focused, smaller city, friendly",
    housing: "€500-800/mo",
    rating: 4.4,
    reviews: [
      { name: "Siddharth M.", text: "ASML connection alone makes it worth it. Got a job there after graduation.", rating: 5 },
      { name: "Diya K.", text: "Orientation year visa is amazing. Stayed and found a job easily.", rating: 4 },
    ],
    tags: ["Tech", "Affordable", "ASML Hub", "English Programs"],
    matchScore: 86,
    pros: ["ASML & Philips hub", "English programs", "Orientation year visa", "Affordable"],
    cons: ["Smaller city", "Less prestigious", "Limited social life"],
    applyUrl: "#",
    videoTour: "#",
  },
];

export const scholarships = [
  {
    id: "daad",
    name: "DAAD Scholarship",
    country: "Germany",
    flag: "🇩🇪",
    amount: "€934/month",
    amountINR: "₹83,000/month",
    type: "Government",
    deadline: "October 15, 2025",
    duration: "24 months",
    coverage: ["Tuition", "Living stipend", "Health insurance", "Travel allowance"],
    eligibility: "Bachelor's degree, CGPA 3.0+, under 32 years",
    competitiveness: "High",
    successRate: "12%",
    description: "Germany's largest scholarship program for international students pursuing graduate degrees at German universities.",
    link: "#",
    matchScore: 88,
    tags: ["Fully Funded", "Government", "STEM Friendly"],
  },
  {
    id: "chevening",
    name: "Chevening Scholarship",
    country: "United Kingdom",
    flag: "🇬🇧",
    amount: "Full funding",
    amountINR: "₹45L (total)",
    type: "Government",
    deadline: "November 5, 2025",
    duration: "12 months",
    coverage: ["Full tuition", "Living expenses", "Travel", "Thesis grant"],
    eligibility: "2+ years work experience, strong leadership",
    competitiveness: "Very High",
    successRate: "3%",
    description: "UK Government's flagship scholarship for future leaders worldwide. All-inclusive funding for one-year master's programs.",
    link: "#",
    matchScore: 72,
    tags: ["Fully Funded", "Leadership", "Prestige"],
  },
  {
    id: "orange-tulip",
    name: "Orange Tulip Scholarship",
    country: "Netherlands",
    flag: "🇳🇱",
    amount: "€5,000-€25,000",
    amountINR: "₹4.5L - ₹22.5L",
    type: "University",
    deadline: "March 1, 2025",
    duration: "Program length",
    coverage: ["Partial/Full tuition"],
    eligibility: "Indian passport, enrolled at Dutch institution",
    competitiveness: "Medium",
    successRate: "28%",
    description: "Nuffic scholarship specifically for Indian students at participating Dutch universities.",
    link: "#",
    matchScore: 91,
    tags: ["India-Specific", "Netherlands", "Partial Funding"],
  },
  {
    id: "pearson",
    name: "Lester B. Pearson Scholarship",
    country: "Canada",
    flag: "🇨🇦",
    amount: "Full funding",
    amountINR: "₹1.2Cr (total)",
    type: "University",
    deadline: "November 15, 2025",
    duration: "48 months",
    coverage: ["Tuition", "Books", "Incidental fees", "Full residence support"],
    eligibility: "Exceptional academic achievement + leadership",
    competitiveness: "Extremely High",
    successRate: "0.1%",
    description: "University of Toronto's most prestigious international scholarship. Extremely competitive but fully transforms your future.",
    link: "#",
    matchScore: 65,
    tags: ["Fully Funded", "Prestige", "Leadership"],
  },
  {
    id: "deutschland",
    name: "Deutschlandstipendium",
    country: "Germany",
    flag: "🇩🇪",
    amount: "€300/month",
    amountINR: "₹27,000/month",
    type: "Mixed (Govt + Private)",
    deadline: "University-specific",
    duration: "12 months (renewable)",
    coverage: ["Monthly stipend"],
    eligibility: "Enrolled at German university, academic excellence",
    competitiveness: "Medium",
    successRate: "32%",
    description: "Germany's merit-based national scholarship co-funded by private donors and the federal government.",
    link: "#",
    matchScore: 94,
    tags: ["Merit-Based", "Renewable", "Multiple Universities"],
  },
  {
    id: "vanier",
    name: "Vanier Canada Graduate Scholarships",
    country: "Canada",
    flag: "🇨🇦",
    amount: "CAD $50,000/year",
    amountINR: "₹30L/year",
    type: "Government",
    deadline: "October 25, 2025",
    duration: "36 months",
    coverage: ["Full living stipend"],
    eligibility: "Doctoral candidates, research excellence",
    competitiveness: "Very High",
    successRate: "5%",
    description: "Canada's premier scholarship for doctoral students with demonstrated leadership skills and top-tier academic achievement.",
    link: "#",
    matchScore: 58,
    tags: ["PhD", "Government", "Leadership"],
  },
];

export const visaData = {
  germany: {
    country: "Germany",
    flag: "🇩🇪",
    visaName: "German Student Visa (National Visa Type D)",
    processingTime: "4-8 weeks",
    fee: "€75",
    successRate: "87%",
    difficulty: "Medium",
    workRights: "120 full days / 240 half days per year",
    postGrad: "18 months job seeker visa",
    prEligible: true,
    prYears: 5,
    embassy: {
      name: "German Embassy New Delhi",
      address: "6/50G, Shantipath, Chanakyapuri, New Delhi - 110021",
      phone: "+91-11-4419-9199",
      website: "https://india.diplo.de",
      appointmentWait: "3-4 weeks",
    },
    documents: [
      { name: "Completed Visa Application Form", required: true, tip: "Fill online at visaentscheidung.de" },
      { name: "Valid Passport (2+ years validity)", required: true, tip: "Must have 2 blank pages" },
      { name: "2 Biometric Passport Photos", required: true, tip: "White background, recent 6 months" },
      { name: "University Admission Letter", required: true, tip: "Original + 2 copies" },
      { name: "Proof of Financial Resources", required: true, tip: "Blocked account (€11,208/year) at Deutsche Bank" },
      { name: "Health Insurance Certificate", required: true, tip: "Public insurance preferred (TK, AOK)" },
      { name: "Academic Transcripts (all degrees)", required: true, tip: "Notarized + apostilled" },
      { name: "Language Certificates", required: false, tip: "IELTS 6.5+ or TestDaF if program in German" },
      { name: "CV/Resume", required: true, tip: "Europass format recommended" },
      { name: "Motivation Letter", required: true, tip: "1-2 pages, specific to university" },
      { name: "APS Certificate (for Indian students)", required: true, tip: "Book APS appointment early — 8-12 week process" },
    ],
    timeline: [
      { phase: "APS Appointment Booking", duration: "1-2 weeks", timing: "10-12 months before", status: "pending", description: "Book your APS (Academic Evaluation Centre) appointment for degree verification" },
      { phase: "APS Interview & Processing", duration: "8-12 weeks", timing: "9-10 months before", status: "pending", description: "Attend APS interview, submit documents, receive APS certificate" },
      { phase: "University Applications", duration: "2-4 weeks", timing: "7-9 months before", status: "pending", description: "Apply to 5-8 universities on Uni-Assist and directly" },
      { phase: "University Acceptance", duration: "6-10 weeks", timing: "5-7 months before", status: "pending", description: "Wait for acceptance letters, compare offers, confirm enrollment" },
      { phase: "Blocked Account Setup", duration: "1-2 weeks", timing: "4-5 months before", status: "pending", description: "Open Deutsche Bank or Fintiba blocked account with €11,208" },
      { phase: "Health Insurance", duration: "1 week", timing: "4 months before", status: "pending", description: "Get German public health insurance (TK, AOK, or Barmer)" },
      { phase: "Visa Application Submission", duration: "1 day", timing: "3-4 months before", status: "pending", description: "Submit complete application at German Embassy New Delhi" },
      { phase: "Visa Processing", duration: "4-8 weeks", timing: "2-3 months before", status: "pending", description: "Embassy reviews your application and makes a decision" },
      { phase: "Visa Collection & Travel", duration: "1-2 weeks", timing: "1-2 months before", status: "pending", description: "Collect visa, book flights, prepare for arrival" },
    ],
    checklist: [
      "Check APS requirements for your Indian university",
      "Start German language learning (B1 useful)",
      "Research blocked account providers",
      "Join student groups for your target university",
      "Research accommodation options early",
    ],
    interviewTips: [
      "Dress professionally and arrive 10 minutes early",
      "Know your university, program and career goals clearly",
      "Explain why Germany specifically (not just Europe)",
      "Show proof of intent to return or future plans",
      "Have all documents in the exact order they ask",
    ],
    riskScore: 23,
    faq: [
      { q: "What is the APS certificate?", a: "APS (Akademische Prüfstelle) is mandatory for Indian students applying to German universities. It verifies your academic credentials. Budget 3-4 months for this process." },
      { q: "How much money do I need in the blocked account?", a: "Currently €11,208 for one year (€934/month). This must be in a specially designated 'blocked account' that releases monthly after arrival." },
      { q: "Can I work while studying?", a: "Yes, you can work 120 full days or 240 half days per year. Many students work 20 hours/week and earn €600-800/month." },
    ],
  },
  canada: {
    country: "Canada",
    flag: "🇨🇦",
    visaName: "Canadian Study Permit",
    processingTime: "4-16 weeks",
    fee: "CAD $150",
    successRate: "60%",
    difficulty: "Easy",
    workRights: "20 hrs/week during studies, unlimited after",
    postGrad: "PGWP: up to 3 years",
    prEligible: true,
    prYears: 3,
    timeline: [
      { phase: "University Application", duration: "3-4 weeks", timing: "12 months before", status: "pending", description: "Apply to Canadian universities" },
      { phase: "Acceptance + LOA", duration: "6-8 weeks", timing: "9 months before", status: "pending", description: "Receive Letter of Acceptance" },
      { phase: "Study Permit Application", duration: "1 day", timing: "6 months before", status: "pending", description: "Apply online via IRCC portal" },
      { phase: "Biometrics Collection", duration: "1-2 weeks", timing: "5 months before", status: "pending", description: "Visit VFS Global for biometrics" },
      { phase: "Visa Processing", duration: "4-16 weeks", timing: "3-4 months before", status: "pending", description: "IRCC processes your application" },
      { phase: "Pre-arrival", duration: "2 weeks", timing: "1 month before", status: "pending", description: "Book flights, accommodation, GIC setup" },
    ],
    documents: [
      { name: "Valid Passport", required: true },
      { name: "Letter of Acceptance", required: true },
      { name: "Proof of Financial Support (GIC - CAD $20,635)", required: true },
      { name: "Academic Transcripts", required: true },
      { name: "Biometric Enrolment", required: true },
      { name: "Statement of Purpose", required: true },
    ],
    checklist: ["Open GIC account", "Get SDS eligible IELTS score", "Apply early for faster processing"],
    interviewTips: ["Be honest about your study plans", "Show strong ties to home country"],
    riskScore: 35,
    faq: [],
    embassy: {
      name: "VFS Global (Canadian visa)",
      address: "Multiple centers across India",
      phone: "+91-22-6797-8400",
      website: "https://www.vfsglobal.ca/canada/india/",
      appointmentWait: "1-2 weeks",
    },
  },
};

export const aiReport = {
  userId: "demo-001",
  generatedAt: "2024-12-01",
  overallScore: 92,
  readinessLevel: "High",
  topCountry: "Germany",
  confidenceLevel: "94%",
  summary: "Based on your academic profile (CGPA 8.4, IELTS 7.5), target field (AI/ML), budget (₹25L), and career goals, Germany is your optimal destination. You qualify for free/low tuition programs and your profile is competitive for DAAD scholarship.",
  strengths: [
    "Strong CGPA (8.4/10) — Top 20% applicant profile",
    "Excellent IELTS score (7.5) — Exceeds most requirements",
    "Relevant field (AI/ML) — High demand in all target countries",
    "Work experience (1 year) — Valued by universities",
  ],
  improvements: [
    "Consider TOEFL as backup for US fallback options",
    "Research publications would strengthen profile",
    "SOP needs to emphasize research interest",
  ],
  alternativeCountries: ["Canada", "Netherlands", "United Kingdom"],
  careerFit: {
    score: 91,
    roles: [
      { title: "Machine Learning Engineer", demand: "Very High", avgSalary: "€68,000", growth: "+38%" },
      { title: "Data Scientist", demand: "High", avgSalary: "€62,000", growth: "+28%" },
      { title: "AI Research Scientist", demand: "High", avgSalary: "€75,000", growth: "+45%" },
      { title: "Software Engineer (AI)", demand: "Very High", avgSalary: "€65,000", growth: "+22%" },
    ],
  },
  universities: ["tum", "rwth", "tue"],
  scholarships: ["daad", "deutschland", "orange-tulip"],
  visaPathway: {
    country: "Germany",
    steps: ["APS Certificate", "University Application", "Blocked Account", "Visa Application"],
    timeline: "10-12 months",
    risk: "Low",
  },
  expectedSalary: {
    entry: "€52,000",
    mid: "€68,000",
    senior: "€95,000",
    currency: "EUR",
    country: "Germany",
  },
  roi: {
    totalCost: "₹18L (2 years)",
    yearOneIncome: "€52,000 (~₹47L)",
    paybackYears: 2.3,
    tenYearWealth: "₹4.2Cr",
    rateOfReturn: "340%",
  },
  livingCosts: {
    country: "Germany",
    city: "Munich",
    rent: "€700",
    food: "€200",
    transport: "€100",
    utilities: "€80",
    entertainment: "€100",
    total: "€1,180",
    totalINR: "₹1,06,000",
    partTimeEarning: "€600",
    netMonthly: "€580",
  },
  timeline: [
    { month: "Jan 2025", task: "Book APS appointment", type: "visa" },
    { month: "Feb 2025", task: "Finalize SOP & LORs", type: "application" },
    { month: "Mar 2025", task: "Apply to TUM, RWTH, TU/e", type: "application" },
    { month: "Apr 2025", task: "APS interview", type: "visa" },
    { month: "May 2025", task: "Open blocked account", type: "financial" },
    { month: "Jun 2025", task: "Receive university offer", type: "milestone" },
    { month: "Jul 2025", task: "Apply for student visa", type: "visa" },
    { month: "Sep 2025", task: "Fly to Germany ✈️", type: "milestone" },
  ],
  language: {
    required: "German B1 (recommended)",
    programLanguage: "English",
    difficulty: "Medium",
    timeToLearn: "6-9 months",
    resources: ["Duolingo", "Goethe Institut", "DW Learn German"],
  },
  risks: [
    { risk: "APS rejection", probability: "Low (8%)", mitigation: "Ensure all Indian transcripts are genuine and attested" },
    { risk: "Blocked account delay", probability: "Low (12%)", mitigation: "Apply to Deutsche Bank/Fintiba 3 months early" },
    { risk: "University rejection", probability: "Medium (25%)", mitigation: "Apply to 8+ universities across safety/target/reach" },
    { risk: "Currency fluctuation", probability: "Medium", mitigation: "Maintain 6-month expense buffer in EUR" },
  ],
  recommendations: [
    "Apply to TUM as your top choice — your profile matches 94% of their accepted students",
    "Apply for DAAD scholarship immediately — deadline Oct 15",
    "Start APS process NOW — it takes 8-12 weeks",
    "Join the TUM India WhatsApp group for tips and connections",
    "Start German A1-B1 on Duolingo + Goethe Institut",
  ],
};

export const chatMessages = [
  {
    id: 1,
    role: "assistant" as const,
    content: "Hi Aryan! 👋 I'm Pathora AI, your personal relocation advisor. I've analyzed your profile and I'm ready to answer any questions about studying abroad. What would you like to know?",
    timestamp: "10:00 AM",
  },
  {
    id: 2,
    role: "user" as const,
    content: "Can I get into Germany with my profile?",
    timestamp: "10:01 AM",
  },
  {
    id: 3,
    role: "assistant" as const,
    content: "Yes, absolutely! Your profile (CGPA 8.4 + IELTS 7.5 + 1 year work experience) is competitive for Germany. Here's my breakdown:\n\n**TUM (Rank #50):** Your CGPA is above their median (8.0). You have ~65% chance of admission.\n\n**RWTH Aachen (Rank #106):** Strong match — ~78% admission chance.\n\n**Key things to do:**\n1. Complete APS verification first (takes 8-12 weeks)\n2. Apply by May 31 for winter intake\n3. Get DAAD scholarship application ready by October\n\nWould you like a detailed university shortlist?",
    timestamp: "10:01 AM",
  },
  {
    id: 4,
    role: "user" as const,
    content: "What about Canada vs Germany for AI/ML?",
    timestamp: "10:02 AM",
  },
  {
    id: 5,
    role: "assistant" as const,
    content: "Great question! Here's the honest comparison for **AI/ML specifically**:\n\n| Factor | Germany | Canada |\n|--------|---------|--------|\n| Tuition | ✅ FREE | ❌ CAD $30K/yr |\n| AI Research | ✅ Excellent | ✅ World-class |\n| Salary | €65K | CAD $110K |\n| PR Path | 5 years | 3 years ✅ |\n| Job Market | Strong in EU | Strong in NA |\n\n**My recommendation for you:** Germany first. You save ₹18L+ on tuition, then if you want North American opportunities, Germany's EU Blue Card gives you mobility.\n\nCanada makes sense if PR in 3 years is your #1 priority.\n\nWhat matters more to you — lower cost or faster PR?",
    timestamp: "10:02 AM",
  },
];

export const referralData = {
  code: "ARYAN2024",
  totalReferrals: 7,
  successfulReferrals: 4,
  pendingReferrals: 3,
  totalEarnings: "₹14,000",
  rewardPerReferral: "₹2,000",
  tier: "Gold",
  nextTier: "Platinum",
  referralsToNextTier: 3,
  leaderboard: [
    { rank: 1, name: "Rahul S.", referrals: 23, earnings: "₹46,000", badge: "🏆" },
    { rank: 2, name: "Priya M.", referrals: 19, earnings: "₹38,000", badge: "🥈" },
    { rank: 3, name: "Vikram K.", referrals: 15, earnings: "₹30,000", badge: "🥉" },
    { rank: 4, name: "Sneha P.", referrals: 12, earnings: "₹24,000", badge: "⭐" },
    { rank: 5, name: "Aryan M.", referrals: 7, earnings: "₹14,000", badge: "⭐", isYou: true },
  ],
};

export const adminStats = {
  totalUsers: 12847,
  activeUsers: 3241,
  reportsGenerated: 9634,
  countriesAnalyzed: 6,
  universitiesListed: 48,
  scholarshipsListed: 230,
  avgSessionTime: "18.4 min",
  conversionRate: "34.2%",
  npsScore: 72,
  monthlyGrowth: 23.4,
  userGrowth: [
    { month: "Jul", users: 2100 },
    { month: "Aug", users: 3400 },
    { month: "Sep", users: 5200 },
    { month: "Oct", users: 7800 },
    { month: "Nov", users: 10400 },
    { month: "Dec", users: 12847 },
  ],
  topCountries: [
    { country: "Germany", interest: 42, flag: "🇩🇪" },
    { country: "Canada", interest: 31, flag: "🇨🇦" },
    { country: "UK", interest: 14, flag: "🇬🇧" },
    { country: "Australia", interest: 8, flag: "🇦🇺" },
    { country: "Netherlands", interest: 5, flag: "🇳🇱" },
  ],
  recentUsers: [
    { name: "Priya Sharma", email: "priya@gmail.com", country: "Germany", status: "Report Ready", joined: "2 min ago" },
    { name: "Rahul Gupta", email: "rahul@gmail.com", country: "Canada", status: "Questionnaire", joined: "8 min ago" },
    { name: "Anjali Patel", email: "anjali@gmail.com", country: "UK", status: "Dashboard", joined: "15 min ago" },
    { name: "Vikram Singh", email: "vikram@gmail.com", country: "Netherlands", status: "Report Ready", joined: "23 min ago" },
    { name: "Meera Nair", email: "meera@gmail.com", country: "Australia", status: "Questionnaire", joined: "31 min ago" },
  ],
};
